version: '3'
services:
  web-forum:
    container_name: web-forum
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:cached
    environment:
      SEED: 1
      PORT: 3000
      SESSION_NAME: sample
      SESSION_SECRET: sample
      MYSQL_DB: forum
      MYSQL_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_CONN_LIMIT: 100
    depends_on:
      - wait
    command: npm run serve

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: forum
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: db:3306
      TIMEOUT: 60
    depends_on:
      - db
